# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TemporalTables
                                 A QGIS plugin
 Temportal tables for QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-06-01
        copyright            : (C) 2019 by OpenGeoLabs s.r.o
        email                : jachym.cepicky@opengeolabs.cz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TemporalTables class from file TemporalTables.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .temporal_tables import TemporalTables
    return TemporalTables(iface)
