# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FiberPlanITConvert
                                 A QGIS plugin
 Convert input files to output FiberPlanIT shapefiles
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-26
        copyright            : (C) 2019 by GISMentors
        email                : info@gismentors.cz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FiberPlanITConvert class from file FiberPlanITConvert.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fiberplanitconvert import FiberPlanITConvert
    return FiberPlanITConvert(iface)
