# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SaveViews
                                 A QGIS plugin
 Plugin saves map image for every feature in the layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-03-06
        copyright            : (C) 2020 by GISMentors
        email                : info@gismentors.cz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SaveViews class from file SaveViews.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .save_views import SaveViews
    return SaveViews(iface)
